### PR TITLE
add mod labyrinth themes

### PR DESCRIPTION
**Pull request by lunofe**
themes using variations of gray as seen on modrinth.

### CODE REVIEW

**Comment by Scrumplex** [comment]
I wasn't too sure about the naming of these themes, so I asked in the MR Discord.

Response of Modrinth staff (text transcript below)

> Modrinth is a trademark. I'd probably recommend you avoid using the name like that since it is a name for something you created for your product and isn't directly related to a Modrinth product or service. You could perhaps pick some sort of Greek name or something maze or labyrinth related to allude to Modrinth perhaps?

Perhaps you could just call the themes "Maze"? "Modmaze" if you want to be more cheeky :D

**Comment by lunofe** [comment]
Ugh. You gotta love companies insisting on their trademark in such superfluous proportions. Well, guess I'll find another name for it then, perhaps *Mod (Laby)rinth* is far enough away from the trademark?

**Comment by Scrumplex** [comment]
> Well, guess I'll find another name for it then, perhaps _Mod (Laby)rinth_ is far enough away from the trademark? Or is that too cheeky 🤔

I'd say that's fine

**Comment by TheKodeToad** [comment]
I think you can still write Modrinth in the description?

**Pull request merged**
