### PR TITLE
Add Scarlett Pink theme

### PR DESCRIPTION
**Pull request by ScarlettPPC**

### CODE REVIEW

**Comment by ScarlettPPC** [comment]
There's a "resources" directory which appears empty but has an empty ".keep" file. Not sure what the matter with that was so I added it manually.

**Review by Scrumplex — APPROVED** [review]
Thanks!

**Comment by Scrumplex** [comment]
> There's a "resources" directory which appears empty but has an empty ".keep" file. Not sure what the matter with that was so I added it manually.

Some older versions of Prism Launcher failed loading themes if they didn't have a `resources` folder. It's just here for compatibility with those versions

**Comment by TheKodeToad** [comment]
@ScarlettPPC You might like to add this to the wiki page https://prismlauncher.org/wiki/getting-started/change-themes/#themes-currently-available !

**Pull request merged**
